import { useEffect, useState } from "react";
import "bootstrap/dist/css/bootstrap.css";

//Lotties
import Lottie from "react-lottie";
import pokeballLoading from "../public/lotties/pikachu.json";

//  Components
import Head from "next/head";
import Loading from "../components/loading";
import Navbar from "../components/navbar";
import PokemonList from "../components/pokemon-list";
import PokemonCard from "../components/pokemon-card";
export default function Home() {
  const [loading, setLoading] = useState(true);
  const [pokemonList, setPokemonList] = useState([]);
  const switchLoading = () => {
    setTimeout(() => setLoading(!loading), 5000);
  };
  useEffect(() => switchLoading(), null);

  const styles = {
    height: "100vh",
    width: "100vw",
  };

  // Optios to lottie
  const defaultOptions = {
    loop: true,
    autoplay: true,
    animationData: pokeballLoading,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice",
    },
  };

  return (
    <>
      <Head>
        <title>Pokedex NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      {/* {loading && <Loading />} */}
      <div className="container" style={styles}>
        <Navbar />
        <div className="row m-0 p-0 h-100 w-100">
          <div className="col-3  m-0 p-0 h-100">filters</div>
          <div className="col-9 m-0 p-0 ">
            <PokemonList>
              {pokemonList.length > 0 ? (
                pokemonList.map((pokemon) => {
                  return <div key={pokemon.id}>{pokemon}</div>;
                  // return <PokemonCard pokemonData={pokemon} key={pokemon.id} />;
                })
              ) : (
                <div className="d-flex flex-column align-items-center h-100 w-100 pt-5">
                  <span>No found Pokemon</span>
                  <div className="h-25 w-25">
                    <Lottie options={defaultOptions} />
                  </div>
                </div>
              )}
            </PokemonList>
          </div>
        </div>
        {/* <div className="col-12 col-md-3">
          Img
        </div> */}
      </div>
    </>
  );
}
